### ISSUE TITLE
1.19?

### ISSUE THREAD

**Issue by ghost** [agnor99/passive-chunk-pregenerator#1]

**Comment by TechPro424** [comment]
1.19.2?

**Comment by TechPro424** [comment]
Please release 1.19.2

**Comment by justliliandev** [comment]
The 1.19.2 version is coded, but I didn't get to publish it yet, will do so this weekend

**Comment by TechPro424** [comment]
@agnor99 pls release

**Comment by ghost** [comment]
@TechPro424 They just said they're going to release it this weekend. Give them some time to finish it.

**Comment by Felix14-v2** [comment]
@agnor99 can you mark it compatible with 1.19.3 on Modrinth? It looks like your amazing mod works great on this version.
Or is it necessary to make some changes under the hood to work properly on 1.19.3?
